CREATE TABLE events (
id SERIAL PRIMARY KEY,
title VARCHAR(255) NOT NULL,
url VARCHAR(255) NOT NULL UNIQUE,
date DATE NOT NULL,
image VARCHAR(255)
);

CREATE TABLE artists (
id SERIAL PRIMARY KEY,
name VARCHAR(255) NOT NULL,
url VARCHAR(255) NOT NULL UNIQUE,
instrument VARCHAR(255),
image VARCHAR(255),
bio TEXT
);

CREATE TABLE event_artists (
id SERIAL PRIMARY KEY,
event_id INTEGER NOT NULL REFERENCES events(id) ON DELETE CASCADE,
artist_id INTEGER NOT NULL REFERENCES artists(id) ON DELETE CASCADE,
UNIQUE(event_id, artist_id)
);

